name: Deploy traefik
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Setup SSH
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #   run: |
      #     command -v ssh-agent >/dev/null
      #     eval $(ssh-agent -s)
      #     echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
      #     mkdir -p ~/.ssh
      #     chmod 700 ~/.ssh
      #     ssh-keyscan "$SSH_HOST" > ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      #     ssh-add -l

      - name: Deploy Traefik
        env:
          BASE_SERVER_PATH: "/data/menyalka/"
          EMAIL: ${{ secrets.EMAIL }}
          HTTP_BASIC_USER: ${{ secrets.HTTP_BASIC_USER }}
          HTTP_BASIC_PWD: ${{ secrets.HTTP_BASIC_PWD }}
          DOMAINNAME: ${{ secrets.DOMAINNAME }}
          TRAEFIK_DIR: ${{ secrets.TRAEFIK_DIR }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          chmod +x ./scripts/ssh-setup.sh
          ./scripts/ssh-setup.sh "$SSH_PRIVATE_KEY" "$SSH_HOST"
          cat ~/.ssh/known_hosts
          ssh-add -l
          chmod -R 755 ./traefik/
          # scp -rp ./traefik/ $SSH_USER@$SSH_HOST:$BASE_SERVER_PATH

          # ssh -i ~/.ssh/key $SSH_USER@$SSH_HOST << EOF
          #   export EMAIL=$EMAIL
          #   export HTTP_BASIC_USER=$HTTP_BASIC_USER
          #   export HTTP_BASIC_PWD=$HTTP_BASIC_PWD
          #   export DOMAINNAME=$DOMAINNAME
          #   export TRAEFIK_DIR=$TRAEFIK_DIR
          #   
          #   touch $TRAEFIK_DIR/acme.json
          #   chmod 600 $TRAEFIK_DIR/acme.json
          #
          #   docker stack deploy -c "$BASE_SERVER_PATH/traefik/docker-compose.yml" traefik
          #
          #   docker system prune -f
          # EOF
